### ISSUE TITLE
SDL 2 Colors not working

### ISSUE THREAD

**Issue by catsanddo** [wmcbrine/PDCurses#114]
When I run testcurs built under SDL 2 I am unable to get any colors to display except for the extended colors.
The first two color tests both look like this.
![image](https://user-images.githubusercontent.com/51969629/122980392-91bade80-d366-11eb-8d6e-d9540f9080da.png)

In my own programs I have been able to get the cursor to change color, but all text remains white on black. Mixing color pairs with A_REVERSE yields odd results. Here the color pair was supposed to be green on red.
![image](https://user-images.githubusercontent.com/51969629/122981356-a6e43d00-d367-11eb-96f6-9ac5e01d988b.png)

I have also tried this on a windows machine and a linux one. All other builds such as wincon or even SDL 2 seem to work just fine.

**Comment by wmcbrine** [comment]
Perhaps related to this: https://github.com/wmcbrine/PDCurses/pull/112 ?

**Comment by Bill-Gray** [comment]
Hmmm... does this happen with WIDE=Y,  or without?  (Text is shown using quite different code if you use wide vs. 8-bit characters.)  I gather results are identical on Windows and Linux,  and that the extended color tests looks like these screen shots?
![image](https://user-images.githubusercontent.com/16679342/123005548-4adbe180-d384-11eb-9e54-44b26a3c6e42.png)
![image](https://user-images.githubusercontent.com/16679342/123005600-5e874800-d384-11eb-8bc8-115d54e81872.png)

When you write "...All other builds such as wincon or even SDL 2..."  do you mean "...or even SDL1"?  What version(s) of SDL2 are you using?  (I'm on 2.0.10,  on Linux;  everything seems to work Just Fine there.)

**Comment by Bill-Gray** [comment]
Just remembered I have a newer box with 2.0.14.  Its 'color attribute macros' screen matches yours (all text is white).  The color cube is correct.  "Colors past 256" matches the screen shot shown above,  except that all the text is white.  And -- as I believe William was thinking -- it applies only in 8-bit,  non-WIDE mode;  if you compile with WIDE=Y,  everything's fine.

**Comment by catsanddo** [comment]
Ah, I did mean SDL 1 there. I was using 2.0.14 when I got those errors. When I compiled with WIDE=Y it worked just fine which I think means that it was related to #112 after all.

**Comment by catsanddo** [comment]
I seem to have missed it before, but wmcbrine mentions in #112 that the issue seems to be resolved when using the git version of SDL. This applies to my case as well. I'm pretty certain these are just two symptoms of the same problem, so I'm closing my issue.
