### ISSUE TITLE
"Visual-noise" in tuidemo

### ISSUE THREAD

**Issue by gvanem** [wmcbrine/PDCurses#116]
Building and running the `tuidemo.exe` program (using `wincon/Makefile.vc`, leaves
this *Visual Noise* on the screen:
![tuidemo-stripes](https://user-images.githubusercontent.com/945271/124460898-3fc77f00-dd90-11eb-99f1-660340c5cb36.png)

Thin vertical stripes (from a previous redraw?)
Any clue as to why?

**Comment by wmcbrine** [comment]
These errors come from the console renderer itself. They're outside the scope of PDCurses' ability to fix, AFAICT (although you could switch to, e.g. the SDL2 backend, if it bothers you enough). You might be able to compensate by adjusting the font size, or other console settings.

**Comment by Bill-Gray** [comment]
It does appear to be a console drawing error.  And that really ought to be a bug report/fix for whichever console it is.  As William notes,  there's not much PDCurses can do here.

I see this was run in 4NT.  Do you see the same problem in cmd.exe?

**Comment by gvanem** [comment]
> ... although you could switch to, e.g., the SDL2 backend

I just crashes. Another issue later maybe?

> Do you see the same problem in cmd.exe?

Yes. But in Win-Term it's fine. Closing.
