### ISSUE TITLE
wincon: _process_key_event() accidentally changes Unicode characters & possibly more bug(s)

### ISSUE THREAD

**Issue by zingchen** [wmcbrine/PDCurses#118]
Keyboard filters (programs that manipulate keyboard events) may inject ASCII and/or Unicode characters in the input buffer, which is read by PDC_get_key() by calling to Win32's ReadConsoleInput() and further handled by _process_key_event(). Examples are Vietnamese keyboard filters for typing Vietnamese, which consume one key from the buffer and inject a string of one or more BS (BackSpace characters) followed by the same number of other [printable, ASCII or not] characters. 

To make it concrete, let's consider Unikey [https://sourceforge.net/projects/unikey/] a Vietnamese keyboard filter with (optional) English user interface. The program supports multiple character sets (e.g. "Unicode", UTF-8, TCVN-3, "Unicode C-string", and so on) but for most Windows applications, including PDcurses Wincon, "Unicode" (i.e. UCS-2) is the correct one to choose. The program supports multiple input (typing) methods (e.g. "Telex", VNI, Microsoft, and so forth) and, for the purpose of illustration, let's choose "Telex". The user may (optionally) select to _always use clipboard for unicode_ but for Win32 console applications, we better leave it unchecked (the default).

For the selected character set ("Unicode") and input method ("Telex", not using clipboard), Vietnamese character **ê** (U+00EA) is typed by the sequence (of keys) **ee** and character **ề** (U+1EC1) is typed by the sequence **êf**, i.e. **eef**. Note that **ê** is composed of one diacritical mark while **ề** of _two_ diacritical marks. 

Note that the key **f**, which generates the second diacritic mark (one added to **ê** to become **ề**) may or may not immediately follow the key sequence **ee**. For example, the Vietnamese word **thềm** (floor) may be typed by **t h e e f m** or **t h e e m f**. The sequence of key events, obtained by ReadConsoleInput() and handled by _process_key_event(), is **t h e** BS **ê** BS **ề m** and **t h e** BS **ê m** BS BS **ề m**, respectively.

**Symptom**. _process_key_event() accidentally changes some Unicode characters, returning a character other than one originally read by ReadConsoleInput(). 

For input key sequence **e e f** for instance, the sequence of calls to ReadConsoleInput() correctly returns **e** BS **ê** BS **ề**, but the respective sequence of calls to _process_key_event() returns **e** BS NUL BS NUL, i.e. the characters **ê** and **ề** are both changed (incorrectly) to NUL.

To prove the symptom, I've inserted 10 debug log points to _process_key_event(), see attached patch1.txt, and collected the trace, see attached trace.txt. The trace is collected for the input key sequence **e e f**. Notice the following lines:

`At: 00004375 - 19:51:09 _process_key_event() - called`
`At: 00004375 - 19:51:09 _process_key_event() - 1. checkpoint: key=234=0xea state=0x20`
`At: 00004375 - 19:51:09 _process_key_event() - H. returning: key 0=0x0`

`At: 00006625 - 19:51:11 _process_key_event() - called`
`At: 00006625 - 19:51:11 _process_key_event() - 1. checkpoint: key=7873=0x1ec1 state=0x20`
`At: 00006625 - 19:51:11 _process_key_event() - H. returning: key 0=0x0`

The NUL (0x0) is obtained with the debug build (DEBUG=Y for GCC compiler). For the "release" build of PDcurses,  _process_key_event() returns 0x3025 (or other random-looking value, depending on whether WIDE=Y is specified), which indicates further bug(s).

[patch1.txt](https://github.com/wmcbrine/PDCurses/files/6777534/patch1.txt)
[trace.txt](https://github.com/wmcbrine/PDCurses/files/6777542/trace.txt)

**Comment by zingchen** [comment]
So, here is my proposed patch: add condition `vk == 0xE7` to the branch "catch printable characters" of _process_key_event().

[patch2.txt](https://github.com/wmcbrine/PDCurses/files/6788221/patch2.txt)

**Comment by wmcbrine** [comment]
Well, it's a pleasantly compact fix, but I'd like to understand a little better what it's doing. Why E7? Would this only fix Vietnamese, or apply more broadly? Are there other characters that should be checked for as well?

**Comment by zingchen** [comment]
0xE7, a.k.a. VK_PACKET, is the virtual key code for a character that is injected to the input buffer. Win32 API documentation states that it is "used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP".

So, I believe every language with non-ASCII alphabet and a complex input method (i.e. other than using dead key) would benefit from the patch.

An alternative patch would be extending kptab[] table to 256 entries, with all-zero 231-st entry (231=0xE7), leaving _process_key_event() intact. This patch is better as it prevents illegal memory access, as vk is used as index to kptab[].

[patch3.txt](https://github.com/wmcbrine/PDCurses/files/6793373/patch3.txt)


___________________
[1] https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by wmcbrine** [comment]
Thanks. Table extended.
