### ISSUE TITLE
Possibly time for a new release?

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#120]
Not sure if there are any important open points but when inspecting https://github.com/wmcbrine/PDCurses/compare/3.9...master there seem to be a lot of changes that actually would make a release reasonable.

**Comment by GitMensch** [comment]
Do you feel the current code to be stable enough for a release?

**Comment by GitMensch** [comment]
If there isn't a new release soon, you may want to have a look at https://github.com/Bill-Gray/PDCursesMod/releases (nearly all of this repo's improvements and bug-fixes should be in there, but the resulting binaries are only ABI-compatible if you specify the right CHTYPE32 during compile; if you can relink then it is likely better to stay with the different default CHTYPE64 of that fork).

**Comment by wmcbrine** [comment]
You should always feel free to use the current source tree. It's complete and functional. The only difference with a formal release is in the documentation.

I'm dithering a bit with what I'm going to do with the version number, to be frank...
