### ISSUE TITLE
show_panel not woking with pad

### ISSUE THREAD

**Issue by GiorgosXou** [wmcbrine/PDCurses#124]
although `PDCurses`'s `hide_panel` function works fine, `show_panel` does not seem to work, example:
```c++
#include <curses.h>
#include <panel.h>


int main( void)
{
    int ch = -1;
    WINDOW *pad1;
    PANEL  *panel1;

    initscr    ();
    noecho     ();
    start_color();
    
    init_pair(1, COLOR_BLUE, COLOR_RED);
    keypad(stdscr, TRUE);

    refresh();

    pad1 = newpad(10,10);
    
    wbkgd   (pad1, COLOR_PAIR(1));
    waddstr (pad1,"Test.");
    prefresh(pad1, 0, 0, 1, 2, 4 , 9);

    panel1 = new_panel(pad1);

    while(ch != 'q' && ch != 'Q')
    {
        ch = getch();
        
        if      (ch == KEY_UP  ) show_panel(panel1);  \\ <-- NOT WORKING
        else if (ch == KEY_DOWN) hide_panel(panel1); 

        update_panels();
        doupdate();
    }
    endwin( );
    return(0);
}
```
**PS.** [`ncurses 6.2`](https://github.com/mirror/ncurses) [won't hide_panel nor show_panel with a pad](https://lists.gnu.org/archive/html/bug-ncurses/2021-10/msg00037.html)

**Comment by Bill-Gray** [comment]
The [2021 Nov 06 `ncurses` patch](https://invisible-mirror.net/archives/ncurses/6.3/ncurses-6.3-20211106.patch.gz) and the [code referenced above by Thomas](https://github.com/mirror/ncurses/blob/c0e5fbfcce224693b3effdd295ee49b6b761b754/ncurses/base/lib_pad.c#L319) caused me to see what's supposed to be going on here,  and I've made corresponding changes to PDCursesMod (something roughly identical would work for PDCurses).  Seems to fix the problems.

One problem remains : the six static variables in question,  `save_(q|p)(min|max)(row|col)`,  really ought to be variables within the WINDOW structure,  as they are in `ncurses`.   That corresponds to the fact that you'd want to "save" those variables on a pad-by-pad basis;  the current PDCursesMod patch only works if you have one pad.  This is quite straightforward to fix,  but it does break binary compatibility.
