### ISSUE TITLE
had to press certain key twice

### ISSUE THREAD

**Issue by igroglaz** [wmcbrine/PDCurses#139]
Hello! Thanks for your awesome lib! ❤️ 

I use PDCurses to develop open-source roguelike game: https://github.com/igroglaz/roglik

Today I've added 5 different races.. I've noticed a very strange bug - when I start the game and choose race # 3 (Elf) - I had to press key '3' twice.... other races works alright - you need to press a key to choose them only once.

- Windows 11 Home, x64, 22H2, 22621.675
- tried static and normal builds
- tried cmd and powershell terminals

**Comment by Bill-Gray** [comment]
(Head scratching here) That is indeed an odd bug.

If you're compiled the demos,  you should have one called `testcurs`.  Run that,  select the 'Input Test',  When you hit '3',   it should say Key Pressed: 3.  Does it?

If it does,  I'd check your code a bit.  At a quick glance,  I see at lines 386 and 486,  you've got situations where if a '3' has been hit,  another character is requested.  (And also if 'r', 'u', 'z', 'i' are hit,  so it may be good to see if those are requiring double hits too.)

I assume when you're just typing at a command prompt,  the '3' works?  (Says somebody who has had a variety of keys stop working on a variety of keyboards... sometimes repairable by cleaning out food crumbs and such,  sometimes not repairable.)

**Comment by igroglaz** [comment]
Bill, thank you!

1) testcurs.exe '3' works as intended
![testcurs_VluXm4xH8X](https://user-images.githubusercontent.com/39904162/200138386-d643ee77-8b97-4714-a164-e457f85ef54b.png)

2) lines 386 works alright too

3) I've noticed this bug appearance in one more case:
when you press 'n' key several times (to restart the game) eventually there will be a moment when you will need to press it twice too...

**Comment by igroglaz** [comment]
Oook. It wass a blunder in my code 🤣 Sorry to bother you, folks! But actually Bill's answer helped me to find the culprit :) THANKS :D
