### ISSUE TITLE
SDL2 port missing support for PDC_PRESERVE_SCREEN

### ISSUE THREAD

**Issue by bjadamson** [wmcbrine/PDCurses#147]
wincon has it here:
https://github.com/wmcbrine/PDCurses/blob/866dbb68b095a8b663e893ef0591fa02c6a0d74a/wincon/pdcscrn.c#L455

dos has it here:
https://github.com/wmcbrine/PDCurses/blob/866dbb68b095a8b663e893ef0591fa02c6a0d74a/dos/pdcscrn.c#L552

ost2 has it here:
https://github.com/wmcbrine/PDCurses/blob/866dbb68b095a8b663e893ef0591fa02c6a0d74a/os2/pdcscrn.c#L127

sdl2 should have it here I believe:
https://github.com/wmcbrine/PDCurses/blob/866dbb68b095a8b663e893ef0591fa02c6a0d74a/sdl2/pdcscrn.c#L340

In the game I'm working on, I immediately destroy stdscr after calling initscr. Adding support PDC_PRESERVE_SCREEN dramatically reduces the visual flickering as I resize the SDL2 window.

**Comment by wmcbrine** [comment]
PDC_PRESERVE_SCREEN is about preserving the content of the original terminal window, from before PDCurses starts rendering. In the case of SDL, as well as X, PDCurses creates a new window, so this option has no meaning. The omission is intentional.

I don't understand what you're talking about with flickering.

**Comment by Bill-Gray** [comment]
Just guessing here,  but... if you remove the lines
```c
if( !pdc_own_window)
    return ERR;
```
from `PDC_resize_screen()` (i.e.,  tell PDCurses : "Go ahead and resize this window,  even though it's not one PDCurses made"),  do you get the desired effect (lack of flicker)?  It _seems_ as if it ought to work.  I can see why using the `SP->_preserve` flag would also work,  but it seems kludgey.
