### ISSUE TITLE
touchoverlap() un-touches parts of lines

### ISSUE THREAD

**Issue by Bill-Gray** [wmcbrine/PDCurses#149]
`touchoverlap()` _should_ cause any part of `win2` that intersects `win1` to be touched.  And it does do that.  But the end result is that (for overlapping lines) only the overlapping columns are marked as touched,  and other touched columns are tossed.  Originally,  an entire line in `win2` may have been touched;  after `touchwin()`,  only those parts of the line that overlap `win1` will be marked as touched.  For example,
```
________
| Win1 |
|      |
|  ___________
|  |aaaa!!!!!|
|  |aaaa!!!!!|  <- Win2
|  |aaaa!!!!!|
___|aaaa!!!!!|
   |zzzzzzzzz|
   |zzzzzzzzz|
   ___________
```
   after calling `touchoverlap()`,  cells in `win2` marked `a` will be touched (as they should be),  those marked `z` will be unaffected (ditto),  and cells marked `!` will be untouched,  even if they were previously touched (that's the problematic bit).  We want to touch the `a` cells without untouching the `!` ones.

Untested fix : I think that
```c
        win2->_firstch[y] = startx;
        win2->_lastch[y] = endx;
```
needs to be replaced with
```c
        if( win2->_firstch[y] == _NO_CHANGE || win2->_lastch[y] < endx)
            win2->_lastch[y] = endx;
        if( win2->_firstch[y] == _NO_CHANGE || win2->_firstch[y] > startx)
            win2->_firstch[y] = startx;
```
Nothing appears to actually use `touchoverlap()` in the various demos or within the library.

**Comment by wmcbrine** [comment]
Agreed.
