### ISSUE TITLE
No rule to make target '../common/libobjs.mif'.  Stop.

### ISSUE THREAD

**Issue by jmsherndon** [wmcbrine/PDCurses#152]
C:\Users\jmshe\OneDrive\Desktop\PDCurses-3.9\wincon\makefile:25: ../common/libobjs.mif: No such file or directory
mingw32-make: *** No rule to make target '../common/libobjs.mif'.  Stop.

im getting this every time i try to compile tried with msvc and gcc dont know if im doing something wrong or if its an issue with the program

**Comment by wmcbrine** [comment]
Perhaps you should clarify the exact command you typed, and the steps you took before that.

The "common" directory does of course contain the file "libobjs.mif", in the original source.

**Comment by jmsherndon** [comment]
well i dont know what happened now im getting a new error. command included

PS D:\program files\codeblocks\mingw\bin> .\mingw32-make -f c:\PDcurses\wincon\makefile
c:\PDcurses\wincon\makefile:90: *** target pattern contains no '%'.  Stop.

**Comment by wmcbrine** [comment]
So, your prompt tells the tale. You should be doing this:

c:
cd \PDCurses\wincon
mingw32-make

Or, alternately:

set PDCURSES_SRCDIR=C:\PDCurses
mingw32-make -f C:\PDCurses\wincon\Makefile

The Makefile doesn't know where it is, unless you set PDCURSES_SRCDIR. Otherwise, it assumes the current directory.

**Comment by jmsherndon** [comment]
PS C:\PDCurses\wincon> set PDCURSES_SCRDIR=C:\PDCurses
PS C:\PDCurses\wincon> mingw32-make -f makefile
makefile:25: "c:\PDcurses"/common/libobjs.mif: Invalid argument
makefile:90: *** target pattern contains no '%'.  Stop.
PS C:\PDCurses\wincon> mingw32-make
Makefile:25: "c:\PDcurses"/common/libobjs.mif: Invalid argument
Makefile:90: *** target pattern contains no '%'.  Stop.

**Comment by jmsherndon** [comment]
WTF moved the makefile from the SAME zipfile i extracted from and it worked, thanks for supporting though
