### ISSUE TITLE
SDL2 build fails for Mac/Linux in Github

### ISSUE THREAD

**Issue by pavkam** [wmcbrine/PDCurses#155]
Not entirely sure what is causing it:

Example of failed build:
https://github.com/pavkam/sharpie/actions/runs/6369436403/job/17289688889

```
Makefile:60: *** Recursive variable 'CC' references itself (eventually).  Stop.
```

It works for other platforms (arm + win).

The build steps I use are here:
https://github.com/pavkam/sharpie/blob/main/.github/workflows/pd-curses-mod-build-and-pack.yml#L101

**Comment by Bill-Gray** [comment]
I think you meant to post this as a PDCursesMod problem.   [I've opened this as an issue there](https://github.com/Bill-Gray/PDCursesMod/issues/302) (with a possible solution).

**Comment by pavkam** [comment]
Oh! Sorry @Bill-Gray, got confused by the build action name. Thanks a million!
