### ISSUE TITLE
Unable to initialize soft label keys

### ISSUE THREAD

**Issue by jgrillout** [wmcbrine/PDCurses#163]
I'm using  PDCurses-3.8
windows 11 and Microsoft visual studio code 
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30153 for x86
I have a very simple test program. Why would slk_init(1) not initialize?

I tried to use the , slk_error()  but it get this build error

I also tried 
int code = slk_init(1);
and code = -1
'slk_error': identifier not found

int main() {
    // Initialize curses
    initscr();
    cbreak();
    noecho();
    keypad(stdscr, TRUE);

    // Initialize soft label keys
    if (slk_init(1) != OK) {
        endwin();
        //fprintf(stderr, "Unable to initialize soft label keys: %s\n");
        fprintf(stderr, "Unable to initialize soft label keys: %s\n", slk_error());

        return 1;
    }
}

**Comment by wmcbrine** [comment]
`slk_error()` doesn't exist, thus the compile fail. Where did you get this idea?

Beyond that, as the docs say: "To use the SLK functions, a call to slk_init() must be made BEFORE initscr() or newterm()". You're calling `initscr()` first.

**Comment by jgrillout** [comment]
slk_error() is an incarnation from ChatGPT.  I’ll try doing what the doc says (my apologies for missing that).
