### ISSUE TITLE
How to build X11 shared library?

### ISSUE THREAD

**Issue by matkuki** [wmcbrine/PDCurses#21]
Hi,

System: Raspbian (Raspberry Pi)

I cannot find any documentation of how to build a shared library (**.so**) on *X11/Linux*.
The *x11/README.md* procedure only builds the static library (**.a**) and *'make install'* throws an error:
```
./install-sh -d -m 755 
install:  no input file specified
Makefile:55: recipe for target 'install' failed
make: *** [install] Error 1
```
Thanks

**Comment by wmcbrine** [comment]
Sorry about that. For X11, unlike other ports, the dynamic and static libraries are supposed to be built at the same time. It appears I broke that back when I moved the configure script to the x11 directory.

A fix for the dynamic build is in the repos now; a fix for make install will come later.

**Comment by matkuki** [comment]
Yes, that fixed it.
Thanks @wmcbrine !

**Comment by wmcbrine** [comment]
Install fix committed.
