### ISSUE TITLE
Win 10 makefile

### ISSUE THREAD

**Issue by Petan1996** [wmcbrine/PDCurses#22]
Hello.
I tried to run makefile with mingw32-make and it gave me this error message.

C:\Windows\system32>cd C:\pdcurs35\win32

C:\pdcurs35\win32>mingw32-make -f gccwin32.mak
gcc -c -O2 -Wall -I.. ../pdcurses/addch.c
gcc -c -O2 -Wall -I.. ../pdcurses/addchstr.c
gcc -c -O2 -Wall -I.. ../pdcurses/addstr.c
gcc -c -O2 -Wall -I.. ../pdcurses/attr.c
gcc -c -O2 -Wall -I.. ../pdcurses/beep.c
gcc -c -O2 -Wall -I.. ../pdcurses/bkgd.c
gcc -c -O2 -Wall -I.. ../pdcurses/border.c
gcc -c -O2 -Wall -I.. ../pdcurses/clear.c
gcc -c -O2 -Wall -I.. ../pdcurses/color.c
gcc -c -O2 -Wall -I.. ../pdcurses/delch.c
gcc -c -O2 -Wall -I.. ../pdcurses/deleteln.c
gcc -c -O2 -Wall -I.. ../pdcurses/deprec.c
gcc -c -O2 -Wall -I.. ../pdcurses/getch.c
gcc -c -O2 -Wall -I.. ../pdcurses/getstr.c
gcc -c -O2 -Wall -I.. ../pdcurses/getyx.c
gcc -c -O2 -Wall -I.. ../pdcurses/inch.c
gcc -c -O2 -Wall -I.. ../pdcurses/inchstr.c
gcc -c -O2 -Wall -I.. ../pdcurses/initscr.c
gcc -c -O2 -Wall -I.. ../pdcurses/inopts.c
gcc -c -O2 -Wall -I.. ../pdcurses/insch.c
gcc -c -O2 -Wall -I.. ../pdcurses/insstr.c
gcc -c -O2 -Wall -I.. ../pdcurses/instr.c
gcc -c -O2 -Wall -I.. ../pdcurses/kernel.c
gcc -c -O2 -Wall -I.. ../pdcurses/keyname.c
gcc -c -O2 -Wall -I.. ../pdcurses/mouse.c
gcc -c -O2 -Wall -I.. ../pdcurses/move.c
gcc -c -O2 -Wall -I.. ../pdcurses/outopts.c
gcc -c -O2 -Wall -I.. ../pdcurses/overlay.c
gcc -c -O2 -Wall -I.. ../pdcurses/pad.c
gcc -c -O2 -Wall -I.. ../pdcurses/panel.c
gcc -c -O2 -Wall -I.. ../pdcurses/printw.c
gcc -c -O2 -Wall -I.. ../pdcurses/refresh.c
gcc -c -O2 -Wall -I.. ../pdcurses/scanw.c
gcc -c -O2 -Wall -I.. ../pdcurses/scr_dump.c
gcc -c -O2 -Wall -I.. ../pdcurses/scroll.c
gcc -c -O2 -Wall -I.. ../pdcurses/slk.c
gcc -c -O2 -Wall -I.. ../pdcurses/termattr.c
gcc -c -O2 -Wall -I.. ../pdcurses/terminfo.c
gcc -c -O2 -Wall -I.. ../pdcurses/touch.c
gcc -c -O2 -Wall -I.. ../pdcurses/util.c
gcc -c -O2 -Wall -I.. ../pdcurses/window.c
gcc -c -O2 -Wall -I.. ../pdcurses/debug.c
gcc -c -O2 -Wall -I.. ../win32/pdcclip.c
gcc -c -O2 -Wall -I.. ../win32/pdcdisp.c
gcc -c -O2 -Wall -I.. ../win32/pdcgetsc.c
gcc -c -O2 -Wall -I.. ../win32/pdckbd.c
gcc -c -O2 -Wall -I.. ../win32/pdcscrn.c
../win32/pdcscrn.c:69:5: error: unknown type name 'PCONSOLE_SCREEN_BUFFER_INFOEX'
     PCONSOLE_SCREEN_BUFFER_INFOEX lpConsoleScreenBufferInfoEx);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:71:5: error: unknown type name 'PCONSOLE_SCREEN_BUFFER_INFOEX'
     PCONSOLE_SCREEN_BUFFER_INFOEX lpConsoleScreenBufferInfoEx);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:73:8: error: unknown type name 'SetConsoleScreenBufferInfoExFn'
 static SetConsoleScreenBufferInfoExFn pSetConsoleScreenBufferInfoEx = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:73:71: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static SetConsoleScreenBufferInfoExFn pSetConsoleScreenBufferInfoEx = NULL;
                                                                       ^~~~
../win32/pdcscrn.c:74:8: error: unknown type name 'GetConsoleScreenBufferInfoExFn'
 static GetConsoleScreenBufferInfoExFn pGetConsoleScreenBufferInfoEx = NULL;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:74:71: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 static GetConsoleScreenBufferInfoExFn pGetConsoleScreenBufferInfoEx = NULL;
                                                                       ^~~~
../win32/pdcscrn.c:77:8: error: unknown type name 'CONSOLE_SCREEN_BUFFER_INFOEX'
 static CONSOLE_SCREEN_BUFFER_INFOEX console_infoex;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c: In function '_set_console_infoex':
../win32/pdcscrn.c:172:10: error: called object 'pSetConsoleScreenBufferInfoEx' is not a function or function pointer
     if (!pSetConsoleScreenBufferInfoEx(pdc_con_out, &console_infoex))
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:73:39: note: declared here
 static SetConsoleScreenBufferInfoExFn pSetConsoleScreenBufferInfoEx = NULL;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c: In function '_init_console_infoex':
../win32/pdcscrn.c:250:19: error: request for member 'cbSize' in something not a structure or union
     console_infoex.cbSize = sizeof(console_infoex);
                   ^
../win32/pdcscrn.c:252:10: error: called object 'pGetConsoleScreenBufferInfoEx' is not a function or function pointer
     if (!pGetConsoleScreenBufferInfoEx(pdc_con_out, &console_infoex))
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:74:39: note: declared here
 static GetConsoleScreenBufferInfoExFn pGetConsoleScreenBufferInfoEx = NULL;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:255:19: error: request for member 'srWindow' in something not a structure or union
     console_infoex.srWindow.Right++;
                   ^
../win32/pdcscrn.c:256:19: error: request for member 'srWindow' in something not a structure or union
     console_infoex.srWindow.Bottom++;
                   ^
../win32/pdcscrn.c: In function '_get_colors':
../win32/pdcscrn.c:266:28: error: request for member 'cbSize' in something not a structure or union
         if (!console_infoex.cbSize)
                            ^
../win32/pdcscrn.c:269:42: error: request for member 'ColorTable' in something not a structure or union
             (COLORREF *)(&(console_infoex.ColorTable));
                                          ^
../win32/pdcscrn.c: In function 'PDC_scr_open':
../win32/pdcscrn.c:455:10: error: 'GetConsoleScreenBufferInfoExFn' undeclared (first use in this function)
         (GetConsoleScreenBufferInfoExFn)GetProcAddress(h_kernel,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:455:10: note: each undeclared identifier is reported only once for each function it appears in
../win32/pdcscrn.c:455:41: error: expected ';' before 'GetProcAddress'
         (GetConsoleScreenBufferInfoExFn)GetProcAddress(h_kernel,
                                         ^~~~~~~~~~~~~~
../win32/pdcscrn.c:458:10: error: 'SetConsoleScreenBufferInfoExFn' undeclared (first use in this function)
         (SetConsoleScreenBufferInfoExFn)GetProcAddress(h_kernel,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:458:41: error: expected ';' before 'GetProcAddress'
         (SetConsoleScreenBufferInfoExFn)GetProcAddress(h_kernel,
                                         ^~~~~~~~~~~~~~
../win32/pdcscrn.c:352:13: warning: variable 'h_kernel' set but not used [-Wunused-but-set-variable]
     HMODULE h_kernel;
             ^~~~~~~~
../win32/pdcscrn.c: In function 'PDC_init_pair':
../win32/pdcscrn.c:612:24: error: 'COMMON_LVB_REVERSE_VIDEO' undeclared (first use in this function)
                 att |= COMMON_LVB_REVERSE_VIDEO;
                        ^~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:617:20: error: 'COMMON_LVB_UNDERSCORE' undeclared (first use in this function)
             att |= COMMON_LVB_UNDERSCORE;
                    ^~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:619:20: error: 'COMMON_LVB_GRID_LVERTICAL' undeclared (first use in this function)
             att |= COMMON_LVB_GRID_LVERTICAL;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c:621:20: error: 'COMMON_LVB_GRID_RVERTICAL' undeclared (first use in this function)
             att |= COMMON_LVB_GRID_RVERTICAL;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
../win32/pdcscrn.c: In function '_get_colors':
../win32/pdcscrn.c:277:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
gccwin32.mak:94: recipe for target 'pdcscrn.o' failed
mingw32-make: *** [pdcscrn.o] Error 1

How can I fix this ?

**Comment by wmcbrine** [comment]
Update your MinGW? It works for me, with a November version.

**Comment by Petan1996** [comment]
Thank you. It works now. I didnt update my MinGW. 👍
