### ISSUE TITLE
Update release page to include the History and at least for current ones include the user guide

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#24]
Please compare https://github.com/wmcbrine/PDCurses/releases with https://github.com/Bill-Gray/PDCurses/releases.

If you want me to I'd adjust the release list as I did for the Bill-Gray repository (using HISTORY.md for the releases post 3.4), but this would need an invitation as Collaborator from @wmcbrine.

**Comment by GitMensch** [comment]
Ping @wmcbrine What do you think about this? Note: If you are OK with this but don't want to do it I'm willing to invest the needed 30 minutes for this.

**Comment by wmcbrine** [comment]
OK, did the releases. Gotta think some more about the user guide. (What I really want is a way to present it online, processed the way GitHub would, except I can't find the right place for it.)

**Comment by GitMensch** [comment]
@wmcbrine 
> What I really want is a way to present it online, processed the way GitHub would, except I can't find the right place for it.

This one may be easy: https://docs.readthedocs.io/en/latest/getting_started.html , it allows webhooks that directly update from git and supports versions as tags (a tag also provides the manual for this with the option for multiple formats, including PDF) http://docs.readthedocs.io/en/latest/webhooks.html

An example how this looks like can be found at https://opencobolide.readthedocs.io/en/latest/index.html
