### ISSUE TITLE
Possibly missing 'SP->key_code = TRUE' setting for KEY_RESIZE in wincon

### ISSUE THREAD

**Issue by ulfalizer** [wmcbrine/PDCurses#30]
"Possibly" because I haven't actually tried it out, but it looks like it might be the cause of some behavior I'm seeing, and I don't see it getting set for `KEY_RESIZE` in `wincon/pdckbd.c`. :)

I'm using the Python wheels from https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses (provided by @cgohlke), which use PDCurses as their backend.

The issue is that `get_wch()` in Python returns `KEY_RESIZE` as a string rather than as an integer when using PDCurses. Looking at the code at https://github.com/python/cpython/blob/master/Modules/_cursesmodule.c#L1222, it probably means that `get_wch()` doesn't return `KEY_CODE_YES` for it.

**Comment by wmcbrine** [comment]
Yep. Thanks. Fix committed.
