### ISSUE TITLE
PDC_DLL_BUILD (was: getch() causes crash, wgetch with return from initscr does not)

### ISSUE THREAD

**Issue by jarruda** [wmcbrine/PDCurses#31]
I am experiencing an issue using pdcurses 3.4-1 (x86-windows, sourced from `vcpkg`) with VS2015.

This issue seems to have been seen at least once before [on StackOverflow](https://stackoverflow.com/questions/33504411/why-the-stdscr-variable-does-not-work-in-pdcurses).

The issue is that when using `stdscr` with `getch`, I receive a crash.

```c
#include <curses.h>

int main()
{
    initscr();
    printw("Hello pdcurses");
    refresh();
    getch();
    endwin();

    return 0;
}
```

The above sample code results in this crash and callstack:
```
Exception thrown: read access violation.
win was 0x6B9E9.
>	pdcurses.dll!wgetch(_win * win) Line 174	C
```

If I modify the code to use the return value of `initscr`, everything works as expected.
```c
#include <curses.h>

int main()
{
    auto scr = initscr();
    printw("Hello pdcurses");
    refresh();
    wgetch(scr);
    endwin();

    return 0;
}
```

Edit:
Stepping through it with a debugger, I discovered that `stdscr` and my local `scr` do not match.  Breakpointing from the start of main, I can see that `stdscr` is not being initialized by `initscr`.

This is a DLL build.

**Comment by wmcbrine** [comment]
Hmm... did you define PDC_DLL_BUILD before including curses.h?

**Comment by jarruda** [comment]
I didn't.  I missed that this was also needed when using the library in addition to the build steps.

Defining it for the project (or above the include) makes the library behave as expected.  :+1:  Thank you for the quick response.

I wonder if modifying curses.h could be added to the build process when preparing a DLL distribution?

**Comment by wmcbrine** [comment]
What I don't get is why it didn't fail with an "unresolved external symbol _stdscr"  error on link with PDC_BUILD_DLL undefined, which is what I get when I try it here.

**Comment by jarruda** [comment]
Replicating my setup should be very easy if you're willing to install `vcpkg`.

```
PS> git clone https://github.com/Microsoft/vcpkg
PS> cd vcpkg
PS> .\bootstrap-vcpkg.bat
PS> .\vcpkg integrate install
PS> .\vcpkg install pdcurses
```

Then copy/paste the above snippet into a new project.  vcpkg takes care of the include paths and linking the library to the project.

I'm also confused as to why there wasn't a linker error.  In fact, if I change the initscr line to:
```c
    stdscr = initscr();
```

I get an access violation writing to that address.

**Comment by wmcbrine** [comment]
Some more discussion here: https://stackoverflow.com/questions/33504411/why-the-stdscr-variable-does-not-work-in-pdcurses/50052560#50052560

I don't think there's anything more to be done here.
