### ISSUE TITLE
SDL2 unable to set colors correctly

### ISSUE THREAD

**Issue by jpcima** [wmcbrine/PDCurses#32]
Hello. In a program which uses SDL2 pdcurses, the colors are not what they should be when I attempt to set a custom scheme. I'm trying to assign tango colors to the set of the basic 16 colors.

Under ncurses and a 256-color xterm, setting a color scheme with this code works.
I put a screen capture of the two, to be able to visualize the difference.

```
    start_color();

    constexpr uint32_t tango_colors[16] = {
        0x2e3436, 0xcc0000, 0x4e9a06, 0xc4a000,
        0x3465a4, 0x75507b, 0x06989a, 0xd3d7cf,
        0x555753, 0xef2929, 0x8ae234, 0xf57900,
        0x729fcf, 0xad7fa8, 0x34e2e2, 0xeeeeec,
    };
    for (unsigned i = 0; i < 16; ++i) {
        unsigned r = (tango_colors[i] >> 16) & 0xff;
        unsigned g = (tango_colors[i] >> 8) & 0xff;
        unsigned b = (tango_colors[i] >> 0) & 0xff;
        init_color(i, r * 1000 / 0xff, g * 1000 / 0xff, b * 1000 / 0xff);
    }
```

![color-pdcurses](https://user-images.githubusercontent.com/17614485/39671086-f0048796-5111-11e8-92bf-4236d5509497.png)

![color-xterm](https://user-images.githubusercontent.com/17614485/39671087-f1c63ae8-5111-11e8-8590-15d0d07cf6c2.png)

**Comment by wmcbrine** [comment]
Since it works in the general case (see the “testcurs” demo), I need a complete example program that works under ncurses and not under PDCurses.

**Comment by jpcima** [comment]
Yes. I should have posted full context in the initial post, [this](https://github.com/jpcima/adljack/blob/2b87c53a904edb654fc58151783649583d7aa355/sources/tui.cc) is the project and relevant source file.
If it is not very helpful, I'll try to recreate it later into a smaller test case.

I'm going to look at the demo code following your suggestion and compare. Maybe pdcurses is sensitive to initialization order in ways that ncurses isn't.

**Comment by jpcima** [comment]
I believe I have managed to reproduce a color problem out of the program.
[Test case](https://github.com/jpcima/PDCurses/commit/d3152bf0ac476758ac51e2ada4f789eec6655b4b)

This program will give two different color outputs in pdcurses and ncurses.
Ncurses backgrounds output in blue, like asked, whereas pdcurses outputs in red.

![testcase](https://user-images.githubusercontent.com/17614485/39674856-f8ef67a4-5152-11e8-88f9-f667a17366e6.png)

**Comment by wmcbrine** [comment]
Yeah, that one's got nothing to do with init_color() per se, but with mixing symbolic and numeric color references (numeric in your init_color() calls, and symbolic in init_pair()). See, by default, PDCurses defines COLOR_BLUE as 1, and COLOR_RED as 4, while ncurses defines COLOR_RED as 1 and COLOR_BLUE as 4. You can change PDCurses' behavior by defining PDC_RGB at build time.

This is handled in testcurs via the colors[] table in colorTest(), which is just a list of the color symbols in the desired order, with init_pair() and init_color() referencing colors[i] instead of just i.

**Comment by jpcima** [comment]
It works now! I have defined `PDC_RGB` and the colors are in order.
Thanks for your help. :+1:
I close this issue since there isn't actually a bug.
