### ISSUE TITLE
Creation of deffont.bmp

### ISSUE THREAD

**Issue by jpcima** [wmcbrine/PDCurses#34]
Hi. The default bitmap font for cp437 has a mention about being generated from bdf fonts.
Is the program which generates this source readily available somewhere?
I would like to generate such bitmaps for different codepages.

**Comment by wmcbrine** [comment]
I honestly have no memory of exactly how I built that file eleven years ago. :) But, you should look at the "sdlfonts" package. There are fonts for other code pages included there:

https://sourceforge.net/projects/pdcurses/files/sdlfonts/1.0/

For a more modern approach, consider the new TTF capability.

**Comment by jpcima** [comment]
> For a more modern approach, consider the new TTF capability.

I like the esthetic of bitmap font vs TTF rendering. Considering there was an update about TTF just recently, I should recheck if the rendering has improved in a way I like.

Now I have written a variant of the tool [bdf2bmp](https://github.com/jpcima/bdf2bmp) to output BMP files in an adequate format, and it has almost identical output with just few bytes of difference.

**Comment by dylanetaft** [comment]
Still relevant and works for what is now called pdcfont.bmp.    Your variant of the tool still works.
