### ISSUE TITLE
Is Alt-Gr implemented?

### ISSUE THREAD

**Issue by thorstenkampe** [wmcbrine/PDCurses#44]
I'm using the Textadept editor which uses PDCurses on Windows. On my German Windows the Alt-Gr key (responsible for `\` and `|` and `{[]}` does not work.

The developer responded (https://foicica.com/lists/code/201609/3349.html)
> I cannot find any mention of AltGr handling in the PDCurses source code,
so I don't think this issue can be fixed :( Sorry.

Is that correct? Can it be fixed or implemented?

**Comment by wmcbrine** [comment]
So far, I'm seeing it work properly if I build PDCurses with WIDE=Y, and use the "Wide Input" test in testcurs (i.e., get_wstr()). Other combinations aren't working correctly. This is with Watcom and Windows 10.

**Comment by wmcbrine** [comment]
...and with MSVC and MinGW, the narrow input also works correctly. I'll have to figure out the problem with Watcom... Anyway, then, the advice is just to build with "WIDE=Y".

**Comment by thorstenkampe** [comment]
Building Textadept with `WIDE=Y` was not successful. The developer of Textadept will continue this ticket (https://foicica.com/lists/code/201811/4852.html). It'll probably take some time.

**Comment by thorstenkampe** [comment]
The author of textadept has committed a patch. I've tested the nightly and it works beautifully. Thanks.
