### ISSUE TITLE
Implement Compatibility with BSD's Curses based Functions

### ISSUE THREAD

**Issue by guilt** [wmcbrine/PDCurses#58]
```
define_key
flushok
fullname
gettmode
is_keypad
is_leaveok
is_pad
is_term_resized
keyok
resizeterm
set_escdelay
set_tabsize
touchoverlap
underend
underscore
wunderend
wunderscore
```

are the functions which require an implementation in PDCurses. This is based on the list found here:
http://netbsd.gw.com/cgi-bin/man-cgi?curses+3+NetBSD-current

This would further enhance compatibility of PDCurses.

**Comment by wmcbrine** [comment]
Do you know of any apps that use these functions?

**Comment by guilt** [comment]
I started working with PDCurses (and Curses in general) today. 

I decided to file this because I felt it would increase the compatibility. I do not know the right answer to your question.

**Comment by guilt** [comment]
I've raised a preliminary / reference PR for this:

https://github.com/wmcbrine/PDCurses/pull/59/commits/ec040c524d7986e2f54e7b633ebe336ec5dbd00e
