### ISSUE TITLE
Build On OSX 10.14.1

### ISSUE THREAD

**Issue by DennisThink** [wmcbrine/PDCurses#60]
I have build this On Win7(64Bit)  and Ubuntu 18.04 and It works well.When I build this on OSX.
It tell me that i need <os2.h>. Does anyone know how to install this lib or how to solve this problem?

**Comment by wmcbrine** [comment]
There's no macOS-specific port of PDCurses. You can use the x11 port (in conjunction with XQuartz), and the sdl2 port (if you install libSDL2). However, macOS already comes standard with ncurses, which you can use to run your curses apps in Terminal.

To get an error about "os2.h", I assume you were trying to build the os2 port? That's actually for the old PC operating system, OS/2.

**Comment by DennisThink** [comment]
Thanks,OS/2 is old PC operating system.I don't know about it.

**Comment by DennisThink** [comment]
I think OS/2 is some of OSX port.sorry.
