### ISSUE TITLE
nc mouse compatibility: missing has_mouse

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#62]
ncurses 5.3 added _nc_has_mouse  to check if the mouse can actually be handled by the library. [ncurses 5.8][2] renamed it to has_mouse. Both functions are not defined in (pd)curses.h.

Questions:

* Should PDCurses' define the "old" _nc_has_mouse along to the current has_mouse?
* Should this/these only be defined if the ncurses mouse compatibility is active (if we add the first, too then at least that should be defined if explicit requested)?
* Is there an option in pdcurses to check if the mouse is active [in terms of "can be used within PDCurses"]? If not: should this function always return TRUE?

[2]:https://lists.gnu.org/archive/html/info-gnu/2011-02/msg00020.html

**Comment by wmcbrine** [comment]
It's not really clear to me what the value of `has_mouse()` is -- you can just check the return value from `mousemask()`?

If it were to be implemented in PDCurses, it should be on a per-platform basis, although all the current platforms do support the mouse. I imagine it would just return True, except in DOS, where it might check for the presence of a driver, as `PDC_mouse_set()` does now.

As for `_nc_has_mouse()`, functions beginning with an underscore are meant to be internal; I don't think we should be copying any of those.

**Comment by wmcbrine** [comment]
In addition to the internal marker, `_nc_has_mouse()` is now deprecated in ncurses.

**Comment by GitMensch** [comment]
I completely agree that _nc_has_mouse should not be implemented (note to the "internal" functions: the _nc_freeall function is explicit documented as public method).

Thank you for the implementation of `has_mouse()`, it really bugged me that PDCurses has a "ncurses compatible interface" but doesn't have this function (I found out when creating this issue that the function has to be checked for in any case as it is "relative new").

Closed as implemented.
