### ISSUE TITLE
Migrating PDCurses 4 (Bill-Gray's repository)

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#64]
If I got the history correct, then https://github.com/Bill-Gray/PDCurses/ was originally created because this repository seemed abandoned.
It started with the ["win32a" extension][1] and as it was active while this repo wasn't got more and more attention and bug-fixes.

We all are excited that this repo got back again but have seen that it won't be possible to simply merge these repositories while it still would be good to have the work done in one place, even if we loose some details we had (possibly only "by default", see below) and loose _some_ of the history.

I want to suggest the following to check if both @wmcbrine and @Bill-Gray are ok with it, to end the split:

* @wmcbrine - Do a 3.9 release on this repo (even if there are not that much changes like in other versions)
* to have a better protection that this repo will be "abandoned" again and to honor his work: add @Bill-Gray to the admins of this repo (an admin may do a release, finish PR, change metadata, invite others)
* include the new vt and wingui flavors as-is (with [a merge filter][2], then `git push` - I volunteer to do that if I'm added as dev here [I don't think this technique will work otherwise and would be totally fine if anyone wants to remove my dev status after this is done])
* check for differences in the makefiles for vt+wingui - adjust, preferring this repo's way (if something seems missing -> create an issue about the difference referencing the commit to make it compatible [if there are adjustments to the makefiles they likely apply to all flavors])
* include the cmake, CI and travis work done in the other repository for all flavors using the same technique (people put work in that and see that as useful, even if the amount of use seemed to be questionable to @wmcbrine before [it won't harm and only get some additional files in], again I volunteer to do this)
* check for necessary adjustments in the sources for vt+wingui - adjust, preferring this repo's way (if something seems missing -> create an issue about the difference referencing the commit to make it compatible [if there are adjustments they may apply to other flavors, too])
* create a PR about changes to "common files" (like the header/demos), handle this "the normal way"
* if there are "reasonable differences" that were made to the Bill-Gray repo but seem conflicting with this repo we could have an #ifdef guard around this, allowing people to work "compatible" to the Bill-Gray repo with an additional option passed to the make
* mark the Bill-Gray repo as read-only
* Do a 4.2 release from this repo (skipping the version numbers that where "used" in the other repositor).

So... @wmcbrine and @Bill-Gray - What do you think about this?

[1]:https://www.projectpluto.com/win32a.htm
[2]:https://bneijt.nl/blog/post/merge-a-subdirectory-of-another-repository-with-git/

**Comment by wmcbrine** [comment]
I appreciate your enthusiasm, but no, I don't support this plan.
