### ISSUE TITLE
Please add configurable WINDRES variable to wincon/Makefile

### ISSUE THREAD

**Issue by elmarco** [wmcbrine/PDCurses#69]
When using cross-compilers, windres has various prefixes. A patch like that helps: 

> diff --git a/wincon/Makefile b/wincon/Makefile
> index 6c5808f..46e0c34 100644
> --- a/wincon/Makefile
> +++ b/wincon/Makefile
> @@ -30,6 +30,7 @@ CC		= gcc
>  AR		= ar
>  STRIP		= strip
>  LINK		= gcc
> +WINDRES         = windres
>  
>  ifeq ($(DEBUG),Y)
>  	CFLAGS  = -g -Wall -DPDCDEBUG
> @@ -87,7 +88,7 @@ $(LIBCURSES) : $(LIBOBJS) $(PDCOBJS) $(RESOURCE)
>  	$(LIBEXE) $(LIBFLAGS) $@ $?
>  
>  pdcurses.o: $(common)/pdcurses.rc
> -	windres -i $(common)/pdcurses.rc pdcurses.o
> +	$(WINDRES) -i $(common)/pdcurses.rc pdcurses.o
>  
>  $(LIBOBJS) $(PDCOBJS) : $(PDCURSES_HEADERS)
>  $(PDCOBJS) : $(PDCURSES_WIN_H)
>

**Comment by wmcbrine** [comment]
OK.

**Comment by wmcbrine** [comment]
https://github.com/wmcbrine/PDCurses/commit/f3a0ce5009cffd360ff4f9c387c4f24e334e38c4

**Comment by elmarco** [comment]
thanks
