### ISSUE TITLE
Broken length clipping in winsnstr() and wins_nwstr()

### ISSUE THREAD

**Issue by ulfalizer** [wmcbrine/PDCurses#72]
`winsnstr()` and `wins_nwstr()` print too many characters when the `n` argument is greater than the length of the string, due to two broken checks:

https://github.com/wmcbrine/PDCurses/blob/7eb7598115c6442db1653f98fff32ab48c923a3c/pdcurses/insstr.c#L85

https://github.com/wmcbrine/PDCurses/blob/7eb7598115c6442db1653f98fff32ab48c923a3c/pdcurses/insstr.c#L193

I think it was meant to be

```c
if (n < 0 || n > len)
```

It looks like the `n < strlen(s)` case might be broken too.

I think this is what's causing https://github.com/zephyrproject-rtos/windows-curses/issues/2.

**Comment by wmcbrine** [comment]
Yikes. Thanks. Shows how much those functions got exercised.
