### ISSUE TITLE
wincon cursor appears even when opposite is set

### ISSUE THREAD

**Issue by dreais** [wmcbrine/PDCurses#75]
after the initscr(), i properly set the `curs_set(0)`, but it seems like it doesn't work for another window. is it an expected behavior?

see screenshot:
![image](https://user-images.githubusercontent.com/55636511/66362163-f57a5980-e981-11e9-8dd8-03d150427194.png)
here, the blinking cursor after M is the cursor of a window created after the curs_set

**Comment by wmcbrine** [comment]
Please provide a complete minimal example program that shows the problem.

**Comment by dreais** [comment]
gonna be a tough one. while i'm doing that, if you have the time, check [this one](https://github.com/dreais/wFita/blob/b00c18f6f6415472e692eb5e1f610e0f4496c500/Sources/Character/monster.c#L26), having the issue.

will come back to you later with a sample!

**Comment by wmcbrine** [comment]
No updates?

**Comment by dreais** [comment]
hello there, sorry for not updating you sooner!
i'm also working with ncurses, and i didn't have the occasion to check on windows since mine is not accessible yet. i'll be closing this issue if that's fine by you, and if i get the chance to try again i will definitely come back. thanks and sorry once again!
