### ISSUE TITLE
inclusion of Bill-Gray's new ports (wingui and vt)

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#76]
This issue is *not* a new version of #64 but a different approach to add the nice new ports.

Plan:

* create a branch from current master for this (all work will be done there, refined until "seems to work", the PR'd for inclusion into master)
* include the new vt and wingui flavors as-is (with a [merge filter][1], then `git push` to the branch - I volunteer to do that, preferably here (if I'm added temporarily as dev), otherwise in a fork of this repo)
* check for differences in the makefiles for vt+wingui - adjust, preferring this repo's way if something is conflicting
* check for necessary adjustments in the sources for vt+wingui - adjust, preferring this repo's way

@wmcbrine What is your opinion about this?

[1]:https://bneijt.nl/blog/post/merge-a-subdirectory-of-another-repository-with-git/

**Comment by GitMensch** [comment]
@wmcbrine what must happen to get the "minimal" (= compatible to this repository and its handling of chtype) version of the wingui and vt ports included in this repository)?

**Comment by wmcbrine** [comment]
My extensive personal review, which will occur on my own time.

**Comment by GitMensch** [comment]
Thank you for considering the inclusion. I'm happy to wait and understand that you need to review it, but I'd love to know more of your timeline for this.
Maybe just drop a note when you start?
(I do **not** urge you but _really hope_ that this will happen in the next months, to provide less reasons to keep the additional repository)

**Comment by GitMensch** [comment]
@wmcbrine Can you please reopen this to keep it tracked as I understand it will be done sometime in the future? Would it help if there'd be a new PR for each port (separately)?
Of course your extensive personal review, whenever it may happen, will also help the shortly-to-renamed fork.
