### ISSUE TITLE
sdl1+sdl2 missing install option

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#77]
sdl2 has ´install` listed as ´.PHONY` target, but doesn't define the target itself. sdl1 has no mention of the `install` target at all.

Suggestion: create the target for both using something like the one used for x11.

**Comment by wmcbrine** [comment]
Yeah, looks like a leftover from d4557e6.

(No, I'm not adding install targets.)

**Comment by GitMensch** [comment]
Broken install target for SDL2 removed with 8a28cf80f66f859f8f4ff7aa3cae93b1d2ca89ab.
@wmcbrine just to add the missing bit of information here: Qhy do you dislike the install target for SDL1 and SDL2 (where it was existing before) but not for X11?

**Comment by wmcbrine** [comment]
It wasn't really existing in SDL2, from my perspective -- it was added and removed before it was ever submitted to me.

And, actually, I *don't* like it in X11. 200K extra just for the configure script and its supporting files? I'd love to dump that. But realistically, I can't. It's established, and people depend on it.

As well, the SDL makefiles aren't Unix-specific, as the X11 stuff is.
