### ISSUE TITLE
doc broken

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#80]
Previously there was a working doc folder that uses GitHub Pages.
After the change in the doc structure this was not updated yet, therefore the link

https://pdcurses.org/doc/

is broken.  
I suggest to adjust the GitHub Pages configuration to the new URL.

**Comment by wmcbrine** [comment]
And where is that URL used? I don't get the point of this issue

**Comment by GitMensch** [comment]
I think it was used somewhere before as I've had a bookmark on it and it worked beforehand.
Instead of fixing the GitHub Pages configuration you may just disable it (if it does not feature pdcurses.org)

**Comment by wmcbrine** [comment]
pdcurses.org IS hosted by GitHub Pages. AFAIK, "docs" is required by them. (There are a couple of other configurations you can use that aren't better.) Originally (2.0-3.6), there was a "doc" folder in the PDCurses tree, for its regular documentation. With 3.7, I started GitHub Pages hosting under "docs", and, in hopes of reducing confusion, I renamed "doc" to "man". Then, with 3.9, I decided the pdcurses.org files could be consolidated down to index.html and CNAME, so I did that, and moved the contents of "man" into "docs", now the unified documentation and web page folder. All of this is described in the git log, BTW.

It's possible that I also used "doc" as a sub-URL in earlier pdcurses.org layouts -- I don't really remember -- but certainly I never linked to it from elsewhere.
