### ISSUE TITLE
can I implement a shell like mysql with this library

### ISSUE THREAD

**Issue by darkgirl** [wmcbrine/PDCurses#81]
hi,
I want to run an application like mysql console.
I wonder if I can use this library to implement it.
can you help, thanks.

**Comment by wmcbrine** [comment]
I'm sure you can, though it may be overkill for that purpose. Anyway, I'm sorry, but this kind of open-ended question is far outside of the appropriate scope for an issue here.

**Comment by wmcbrine** [comment]
See tutorials, like http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/ (mostly still applicable to PDCurses), read the source code of curses-based programs, and read the documentation, is all I can suggest.

**Comment by darkgirl** [comment]
thank you anyway, that's all i need
