### ISSUE TITLE
install hyperion on kali linux by mingw64

### ISSUE THREAD

**Issue by chen12304** [wmcbrine/PDCurses#89]
i have problem on it.why it show this:
kali@kali:~$ sudo i686-mingw64msvc-c++ hyperion-2.3/Src/Crypter/*.cpp -o hyperion.exe
sudo: i686-mingw64msvc-c++: command not found
What command  is right?

**Comment by wmcbrine** [comment]
I don't think that's a PDCurses issue.

**Comment by chen12304** [comment]
> I don't think that's a PDCurses issue.

sorry， I'm a freshman in github
