### ISSUE TITLE
Missing definition of _XOPEN_CURSES?

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#94]
https://pubs.opengroup.org/onlinepubs/7908799/xcurses/curses.h.html says

> The following constant is defined if the implementation supports the indicated revision of the X/Open Curses specification: 
> `_XOPEN_CURSES`

rechecked on AIX curses.h: this says
`#define _XOPEN_CURSES   4002`

PDCurses implements all methods mentioned above, doesn't it?

... Hm, checking the newer version [X/Open Curses, Issue 7 (Reference C094)](https://publications.opengroup.org/c094) this sounds different:

> The material on pages labeled ENHANCED CURSES and the material flagged with the EC-margin legend is available only in cases where the `_XOPEN_CURSES` version test macro is defined.

So... Should PDCurses only defines this if it implements everything, include handling the "Terminfo Source Format" and terminfo database(s)? I'm confused.

**Comment by GitMensch** [comment]
Still wondering, Any thoughts about this @wmcbrine @Bill-Gray?

**Comment by Bill-Gray** [comment]
I'm unclear on this as well.  However,  `curses.h` says,  regarding the `WA_*` #defines,
```
/* For use with attr_t -- X/Open says, "these shall be distinct", so
   this is a non-conforming implementation. */
```
Which would appear to disqualify us from claiming conformance anyway.  I don't know if we have any other disqualifiers.

(I'm kinda unclear on how and why the `WA_*` #defines should be distinct anyway.  Perhaps this just means that,  say, `WA_INVIS` and `WA_ITALIC` can't be the same?  If the meaning is that `A_BLINK` and `WA_BLINK` must be distinct... I don't see the point?  How would `A_BLINK` and `WA_BLINK` actually differ?)

**Comment by wmcbrine** [comment]
The only other thing the spec says about it is "The following constant is defined if the implementation supports the indicated revision of the X/Open Curses specification: _XOPEN_CURSES". I think terminfo would be needed, at least.

**Comment by GitMensch** [comment]
Thanks, then this is out-of-scope.
