### ISSUE TITLE
PDCurses on Plan9 works but is very slow ... how can I figure out what is wrong?

### ISSUE THREAD

**Issue by staalmannen** [wmcbrine/PDCurses#95]
Hi

I recently updated the old PDCurses port to latest git master and made a pull request #93 . As mentioned there, the demos and other curses-based programs I install work but are extremely slow (I first thought they were unresponsive).

CPU load not high (see picture attached) so I am guessing that it has something to do with time measurement and refresh rate or something?

How can I figure out what is wrong? I checked the file "refresh" under pdcurses/ but that did not make me any wiser unfortunately.

![9front_pdcurses_demos](https://user-images.githubusercontent.com/662358/84502478-ad51ca80-acb8-11ea-8b40-97d84fc603a1.png)

**Comment by Bill-Gray** [comment]
Hmmm... are you seeing a long wait and then bam,  the screen is updated?  Do lines appear one at a time?  Or do you see the characters crawl across the screen (in,  say,  "PDCurses Test Program",  can you watch as that particular text is updated?)

I know virtually nothing about Plan9.  I do wonder about `p9napms`,  wherein you call `sleep(ms)`.  On Linux,  that would sleep for `ms` _seconds_,  not milliseconds.  Might be worth just commenting out that line and seeing if it suddenly roars to life (though with no sleep at all,  you'll also see CPU load spike.)

**Comment by staalmannen** [comment]
It is more of the long wait then bam, not like slow line-by-line updates and no slow crawling text updates.

Indeed there is a difference between plan9 sleep and posix sleep. The problem here is that this is built under APE so sleep should be posix.... I will try that.

**Comment by staalmannen** [comment]
Thanks for solving the issue! Good catch! Now I just need to figure out a proper way of doing the ms sleep. nanosleep() caused a crash.
