### ISSUE TITLE
How do i create a .lib file? ( i can only make a .a file)

### ISSUE THREAD

**Issue by kireita** [wmcbrine/PDCurses#99]
Hey there i was able to run the makefile but i get a .a file and i want a .lib file, can someone help me? i have no experience with make files and youtube is not really helping, i just want to integrate the library in my project solution.

i am using Visual Studio 2019 Community edition, and i want to integrate the .lib in my solution, the .a is perfect for visual code but that is currently not my target.

i have mingw  installed but that only generates a .a file
and in the instruction it says you can make a .lib file but i cannot get it to work for the life of me:
![image](https://user-images.githubusercontent.com/25864917/89742003-59841780-da96-11ea-8d13-5e88fa4c1129.png)

i hope someone can help.

thanks in advance.

**Comment by kireita** [comment]
i tried following these instructions:

![image](https://user-images.githubusercontent.com/25864917/89742069-f5ae1e80-da96-11ea-8ce8-71ab846bda6c.png)

but if i try to run: `mingw32-make.exe` all -f Makefile WIDE=Y UTF8=Y `INFOEX=N` 

no lib is generated

**Comment by wmcbrine** [comment]
Generally speaking, you should build it with the same compiler as you use to build the rest of your code. It doesn't make sense to build the library with MinGW and the code that will link to that library with MSVC. (Visual Studio = MSVC (Microsoft Visual C), BTW, in case that wasn't clear.) Open the Visual Studio command line and do `nmake -f Makefile.vc WIDE=Y UTF8=Y`.

**Comment by kireita** [comment]
> Generally speaking, you should build it with the same compiler as you use to build the rest of your code. It doesn't make sense to build the library with MinGW and the code that will link to that library with MSVC. (Visual Studio = MSVC (Microsoft Visual C), BTW, in case that wasn't clear.) Open the Visual Studio command line and do `nmake -f Makefile.vc WIDE=Y UTF8=Y`.

thank you for the clarification on Visual Studio and answering my question , i was able to make the library 

thank you!

PD: I'm sorry for my ignorance about the topic I'm getting so much c++ information and sometimes i cant make head or tales from it.
